name: CI Mentoria

# gatilhos
on: 
  workflow_dispatch: 

jobs:
  tests: 

    #[config do so] (windows/linux/mac, chrome/firefox/edge, ...)  
    runs-on: ubuntu-latest

    #[variaveis] (variáveis de ambiente, chaves de acesso a plataformas, etc.) 
    env:
      API_BASE_URL: 'http://localhost:3000'
      PORT: 4000      
    # [acoes ou passos]
    steps:

      - name: Checkout do Repositório
        uses: actions/checkout@v4

      - name: Instalando das dependências 
        run: npm install 
        
      - name: Iniciar servidor mock
        run: npm run mock-server &
        
      - name: Iniciar servido web
        run: npm run server &

      - name: Executar os testes
        run: npx cypress run &



      
      
